# Generated by Django 5.1.4 on 2025-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="icon",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
