# Generated by Django 5.1.4 on 2025-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
        migrations.AddField(
            model_name="account",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="icon",
            field=models.ImageField(
                blank=True,
                height_field="height",
                upload_to="account_icons/",
                width_field="width",
            ),
        ),
    ]
