# Generated by Django 5.1.4 on 2025-01-06 06:37

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_account_options_account_height_account_width_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="height",
        ),
        migrations.RemoveField(
            model_name="account",
            name="width",
        ),
        migrations.AlterField(
            model_name="account",
            name="icon",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, upload_to="account_icons/"
            ),
        ),
    ]
