# Generated by Django 5.1.4 on 2025-01-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_category_transaction_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="timestamp",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="transaction",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
