# Generated by Django 5.1.4 on 2025-01-06 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_rename_timestamp_transaction_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.category",
            ),
        ),
    ]
