# Generated by Django 5.1.4 on 2025-01-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_category_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.category",
            ),
        ),
    ]
