# Generated by Django 5.1.4 on 2025-01-06 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_remove_category_subcategory_category_parent_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="transactions.category",
            ),
        ),
    ]
