# Generated by Django 5.1.4 on 2025-01-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_category_parent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
